[package]
name = "git-overlay"
version = "0.0.5"
authors = [ "SzB640 <szb640@gmail.com>" ]
description = "Software for overlaying personal files onto a git repository"
edition = "2024"
readme = "README.md"
repository = "https://github.com/szb640/git-overlay"

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.11.11"
ignore = "0.4.33"
log = "0.4.33"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"

[dev-dependencies]
serde_json = "1"
